# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Florian Bufler
email: florian.bufler@gmail.com
description: Florian Bufler is a Cloud Developer @Bosch
domain: fbufler.github.io
baseurl: "" 
url: https://fbufler.github.io
github_username: fbufler
mode: dark #bright or dark (in development)

# Google Analytics
google_analytics: G-KWH5E0QLCH

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  about:
    output: true
    permalink: /:collection/:path/
    
# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
